version: 2
jobs:
  build:
    working_directory: ~/androidtest

    docker:
      - image: cimg/android:2022.12.1-ndk

        environment:
          GRADLE_OPTS: -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy="in-process"
          RUST_VERSION: 1.67.0
      - image: "openjdk:17"
        environment:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64 # 设置JAVA_HOME环境变量
    steps:
      - checkout
      - run:
          name: Run Build and Tests
          command: ./gradlew assembleRelease check -PCARGO_PROFILE=release
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk/app