version: 2
jobs:
  build:
    working_directory: ~/androidtest

    docker:
      - image: "openjdk:17"
      - image: cimg/android:2024.07
    steps:
      - checkout
      - run: ./gradlew androidDependencies
      - run: ./gradlew lint test
      - run:
          name: CheckJavaVersion
          command: java -version
      - run:
          name: Cat JAVA_HOME
          command: echo $JAVA_HOME
      - run:
          name: Cat ANDROID_HOME
          command: echo $ANDROID_HOME
#      - run:
#          name: Run Build and Tests
#          command: ./gradlew assembleRelease
#      - store_artifacts:
#          path: app/build/outputs/apk
#          destination: apk/app