version: 2
jobs:
  build:
    working_directory: ~/androidtest

    docker:
      - image: "openjdk:17"
      - image: circleci/android:api-34
    steps:
      - checkout
      - run:
          name: CheckJavaVersion
          command: java -version
      - run:
          name: Cat JAVA_HOME
          command: echo $JAVA_HOME
      - run:
          name: Run Build and Tests
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk/app